---
- name: Install Chocolatey packages (VirtualBox)
  win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items: {{ choco_pkgs.virtualbox }}
  when: "{{ install_vbox }} == true"

- name: Install Chocolatey packages (VAGRANT)
  win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items: {{ choco_pkgs.vagrant }}